# Generated by Django 2.2.23 on 2021-05-20 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_type', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('EGP', 'EGP')], max_length=3, verbose_name='from currency type')),
                ('to_currency_type', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('EGP', 'EGP')], max_length=3, verbose_name='to currency type')),
                ('times', models.PositiveIntegerField(default=1, verbose_name='times')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_currencies', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Currency',
                'verbose_name_plural': 'User Currencies',
            },
        ),
    ]
